# Generated by Django 5.1.2 on 2025-06-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
