# Generated by Django 5.1.2 on 2025-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_product_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_before',
        ),
        migrations.AddField(
            model_name='product',
            name='price_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
