# Generated by Django 5.1.2 on 2025-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_color',
            field=models.CharField(default='red', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(default='Small', max_length=255),
        ),
    ]
