# Generated by Django 5.1.2 on 2025-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_cartitem_selected_color_cartitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_fee',
            field=models.IntegerField(default=15),
        ),
    ]
